<?php

namespace WA\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{


    public function listByDateDesc()
    {
        $dateMax='2014-12-18';
        $queryBuilder=$this->createQueryBuilder("a");
        $articleList=$queryBuilder->addOrderBy('a.articleDate','DESC')
                        ->where('a.articleDate <= :date')
                        ->setParameter('date', $dateMax)
                        ->getQuery()
                        ->getArrayResult()
                           ;
        return($articleList);



    }

}
